# Generated by Django 3.2.16 on 2023-03-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(help_text='Width:160px X Height:100px', upload_to='pictures/partners'),
        ),
    ]
