# Generated by Django 3.2.16 on 2023-03-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='display_picture',
            field=models.ImageField(help_text='Width: 400px, Height: 400px', upload_to='pictures/team/'),
        ),
    ]
