# Generated by Django 3.2.16 on 2023-03-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(help_text='Width:800 X Height:562', upload_to='pictures/activities/'),
        ),
    ]
