# Generated by Django 3.2.16 on 2023-09-07 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('procurement_request_description', models.TextField(help_text='Give the general information on this request.')),
                ('md_approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=10)),
                ('md_comment', models.TextField(blank=True, null=True)),
                ('chairman_approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=10)),
                ('chairman_comment', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Procurement Request',
                'verbose_name_plural': 'Procurement Requests',
            },
        ),
        migrations.CreateModel(
            name='ProcurementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='Name of Item')),
                ('description', models.TextField(verbose_name='Item description')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reason_for_item_need', models.CharField(help_text='Give the reasons why this item is needed', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('procurement_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurements.procurementrequest')),
            ],
        ),
    ]
