# Generated by Django 3.2.16 on 2023-03-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_picture',
            field=models.ImageField(help_text='Width:600px X Height:600px', upload_to='pictures/products'),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='picture',
            field=models.ImageField(blank=True, help_text='Width:600px X Height:000px', null=True, upload_to='pictures/products/pictures'),
        ),
    ]
